config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root"pins#index"
  get "about" => "pages#about"
  get "team" => "pages#team"
  get "faq" => "pages#faq"
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100>" }

	validates :description, presence:true
	validates :image, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins 

  validates :name, presence: true      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def team
  end

  def faq
  end


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8) 
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
	<nav class="navbar navbar-inverse navbar-default" role="navigation">
    <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Language Dream", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Team", team_path %></li>
      <li><%= link_to "Faq", faq_path %></li>
      <% if user_signed_in? %>
      <li>
        <button type="button" class="btn btn-default navbar-btn">
          <%= link_to new_pin_path do %>
        <span class="glyphicon glyphicon-plus-sign"></span> New Pin
        <% end %>  
        </button>
      </li>
      <li><%= link_to "Settings", edit_user_registration_path %></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>   
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Language Dream</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %> 
<div class="container">
	<% flash.each do |name, msg| %>
	   <%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
<h1>Welcome to Language Dream</h1>
<h2>Teach a Little... Learn a Lot</h2>
</br>
<p>
	<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>
</div>

app/views/pages/about.html.erb
<div class="jumbotron center">
  <div class="container">
   <h1 class="center">About Language Dream</h1>
</br>
	<h2 class="center">Our concept is fun and simple:</h2>
	

	<ul class="list-group left">
  <li class="list-group-item"><span class="glyphicon glyphicon-heart"></span>   Teach a little... Learn a Lot</li>
  <li class="list-group-item"><span class="glyphicon glyphicon-gift"></span>   Use your learning time more efficiently</li>
  <li class="list-group-item"><span class="glyphicon glyphicon-user"></span>   Small class sizes</li>
  <li class="list-group-item"><span class="glyphicon glyphicon-facetime-video"></span>   Classes meet via Google Hangouts</li>
  <li class="list-group-item"><span class="glyphicon glyphicon-globe"></span>   Meet language lovers from around the world</li>
  
</ul>
  </div>
</div>

app/views/pages/faq.html.erb
<div class="jumbotron">
  <div class="container">
  	<h1 class="center">Frequently Asked Questions</h1>

  	</br>

  	<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Who is Language Dream for?</h3>
  </div>
  <div class="panel-body">
    Language Dream is for anyone who is learning a language--especially for those who want to practice speaking with native speakers.
  </div>
  </div>

  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">How does Language Dream work?</h3>
  </div>
  <div class="panel-body">
    It's pretty simple.
  </div>
  </div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Where are classes held?</h3>
  </div>
  <div class="panel-body">
    Online with Google Hangouts. All you need is a device that can use Google Hangouts and a decent internet connection.
  </div>
  </div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">When are classes held?</h3>
  </div>
  <div class="panel-body">
    The classes at Language Dream are crowdsourced, so classes are held whenever a member wants to teach one.
  </div>
  </div>

  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">How much does it cost?</h3>
  </div>
  <div class="panel-body">
    Language Dream is free to try for the first week and membership starts at just $10 a month after that
  </div>
  </div>

  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Why do you charge money--can't it be free?</h3>
  </div>
  <div class="panel-body">
    It takes a lot of time, money and effort to build and run Language Dream, so it costs $. I don't want to work a real job. You will find that you can learn a lot more at Language Dream for a lot less than you would pay at a brick and mortar language school. Plus, you don't even have to get out of bed to attend classes on Language Dream. 
  </div>
  </div>

  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">I don't know how to teach, I'm not a teacher, can I still use Language Dream?</h3>
  </div>
  <div class="panel-body">
    Most Language Dream members are not real teachers. The one thing we are all experts in is our native language. And you don't really have to "teach" in class, as much as just get your students talking in the language. The goal of Language Dream is to be the go to place for people to practice speaking languages. The best class on Language Dream are just great conversations between fun people from around the world.
  </div>
  </div>

 <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">What do I get for VIP membership?</h3>
  </div>
  <div class="panel-body">
    VIP membership costs $50 a month. It enables you to learn as much as you want.  Maybe you also want to support Language Dream by paying more. You can sleep better at night knowing that your money is supporting the Language Dream community.
  </div>
  </div>

  </div>

</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1>Welcome to Language Dream</h1>
<h2>Teach a Little... Learn a Lot</h2>
</br>
<% if user_signed_in? %>
  # do something
  <% else %>
<p>
	<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>
<% end %>
</div>

app/views/pages/team.html.erb
<div class="jumbotron center">
  <div class="container">
   <h1>The Language Dream Team</h1>
   <h4>I'm Ryan, the founder of Language Dream. The concept for Language Dream was born from a problem I had. I was living in Seoul, South Korea and I was frustrated at having to teach a Korean friend English for 1 hour for every hour I wanted to practice speaking Korean. As much as I loved teaching English, I wanted to focus on learning Korean. And I had an idea on how to make that happen.</h4> 
   <h4>I couldn't find anything like it on the web, so I had to build it myself. For the longest time, this was just a dream.</h4> 
   <h4>Language Dream is the never final product of 3+ years of slowly learning how to build a website and getting an MBA at UCLA to learn how to scale a sustainable company.</h4>
   <h4>Feel free to drop me a line, or visit the Language Dream world headquarters at the University of California, Los Angeles.</h4>
   <button type="button" class="btn btn-primary btn-lg">
  	<span class="glyphicon glyphicon-envelope"></span> Email!
	</button>
</br>
	<div class="btn-group">
  		<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-phone"></span>  Call: 310-430-1754</button>
  		<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-map-marker"></span>  Meet: I'm in LA</button>
	</div>

   </div>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
   <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        <%= link_to image_tag(pin.image.url(:medium)), pin %>
        <div class="panel-body">
        <p><%= pin.description %></p>
        <p><strong><%= pin.user.name if pin.user %></strong></p>
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
            <span class="glyphicon glyphicon-edit"></span> Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span> Destroy
            <% end %>
          </div>
        <% end %>
      </div>
      </div>
    <% end %>
</div>
<div class="center">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
		<div class="panel-heading center">	

            <%= image_tag @pin.image.url(:medium) %>
        </div>
        <div class="panel-body">

      <p><%= @pin.description %></p>
      <p><strong><%= @pin.user.name if @pin.user %></strong></p>

<% if @pin.user == current_user %>
  <%= link_to edit_pin_path(@pin) do %><span class="glyphicon glyphicon-edit"></span> Edit
  <% end %>
<% end %>
</div>

</div>
</div>

  